controller_list:
  - name: fake_moveit_inpipe_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
initial:  # Define initial robot poses per group
  - group: moveit_inpipe
    pose: pose_init