robot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: position_controllers/JointTrajectoryController
    joints: [joint_1]

  joint2_position_controller:
    type: position_controllers/JointTrajectoryController
    joints: [joint_2]

  joint3_position_controller:
    type: position_controllers/JointTrajectoryController
    joints: [joint_3]


