robot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  inpipe_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - joint_1
      - joint_2
      - joint_3
    hardware_interface: hardware_interface/PositionJointInterface

